name: "httpx Action"
description: "httpx is a fast and multi-purpose HTTP toolkit allows to run multiple probers using retryablehttp library."
branding:
  icon: "activity"
  color: "blue"

inputs:
  list:
    description: "List of hosts to run HTTP/S Web server probbing"
    required: true
    default: ""

  output:
    description: "File to save output result"
    required: false
    default: "httpx.log"

  flags:
    description: "Additional httpx CLI flags to use"
    required: false

  json:
    description: "Format to save of output file"
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - run: |
        [ ! -x /home/runner/go/bin/httpx ] && GO111MODULE=on go get -v github.com/projectdiscovery/httpx/cmd/httpx@v1.1.0
        [ ! -z ${{ inputs.list }} ] && echo "list=-l ${{ inputs.list}}" >> $GITHUB_ENV
        [ ! -z ${{ inputs.output }} ] && echo "output=-o ${{ inputs.output}}" >> $GITHUB_ENV || echo "output=-o httpx.log" >> $GITHUB_ENV
        [ ! -z ${{ inputs.flags }} ] && echo "flags=${{ inputs.flags }}" >> $GITHUB_ENV
        ${{ inputs.json }} && echo "json=-json" >> $GITHUB_ENV
        echo "/home/runner/go/bin/" >> $GITHUB_PATH
      shell: bash

    - run: |
        httpx \
          ${{ env.list }} \
          ${{ env.output }} \
          ${{ env.json }} \
          ${{ env.flags }}
      shell: bash
